import { ConnectButton } from "@rainbow-me/rainbowkit"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"
import { PlusIcon, SearchIcon } from "@heroicons/react/24/solid"
import { useState } from "react"
import MintCard from "@/components/MintCard"

const Home = () => {
  const [pages, setPages] = useState([
    { id: 1, title: "Cellula 游戏指南", icon: "📘" },
    { id: 2, title: "Pro 工具列表", icon: "🛠️" },
    { id: 3, title: "Web3 集成", icon: "🌐" }
  ])

  const addNewPage = () => {
    const newPage = { id: pages.length + 1, title: "新页面", icon: "📄" }
    setPages([...pages, newPage])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Cellula Pro</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className="bg-white text-[#333] border-b-4 border-[#4CAF50] pixel-font">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4">
              <h1 className="text-2xl font-bold text-[#4CAF50] pixel-text">
                Cellula Pro
              </h1>
            </div>

            <div className="flex items-center space-x-4">
              <ConnectButton />
              {/* <Button className="bg-[#4CAF50] hover:bg-[#45a049] text-white font-bold py-2 px-4 transition duration-150 ease-in-out pixel-button">
                开始使用
              </Button> */}
            </div>
          </div>
        </div>
      </header>
      <main className={`${styles.main} bg-white min-h-screen flex flex-col`}>
        <div className="flex-1 w-full h-full flex-row justify-between">
          <div role="tablist" className="tabs tabs-lifted h-full">
            <input
              type="radio"
              name="my_tabs_2"
              role="tab"
              className="tab"
              aria-label="Mint"
              defaultChecked
            />
            <div
              role="tabpanel"
              className="tab-content bg-base-100 border-base-300 rounded-box p-6"
            >
              <MintCard />
            </div>

            <input
              type="radio"
              name="my_tabs_2"
              role="tab"
              className="tab"
              aria-label="Tab 2"
            />
            <div
              role="tabpanel"
              className="tab-content bg-base-100 border-base-300 rounded-box p-6"
            >
              Tab content 2
            </div>

            <input
              type="radio"
              name="my_tabs_2"
              role="tab"
              className="tab"
              aria-label="Tab 3"
            />
            <div
              role="tabpanel"
              className="tab-content bg-base-100 border-base-300 rounded-box p-6"
            >
              Tab content 3
            </div>
          </div>
          <div></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  )
}

export default Home
